#!/bin/sh

if ! command -v ormolu 1>/dev/null; then
	echo "error: ormolu is not installed" 1>&2
	exit 1
fi

out=$(git diff --cached --name-only src/ test/ | xargs -r ormolu --mode check 2>&1)
if [ $? -ne 0 ]; then
	printf "The following files need to be formated with 'ormolu':\n\n" 1>&2
	printf "%s\n" "${out}" | awk '/^(src|test)/ { printf("\t%s\n", $0) }' 1>&2
	exit 1
fi
